name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 手動で実行できるボタンを出すための魔法

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install markdown jinja2

      - name: Build site
        # srcフォルダに入って実行
        run: python3 build.py
        working-directory: ./src

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src/dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
